name:                asmdc
version:             0.1.0.0
github:              "jkunkee/asmd-gen"
license:             BSD3
author:              "Alexander Lemon"
maintainer:          "amikharemon@gmail.com"
copyright:           "2019 Alexander Lemon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jkunkee/asmd-gen/asmdc#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- bytestring
- text

library:
  source-dirs: src

executables:
  asmdc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asmdc

tests:
  asmdc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asmdc
